spring:
  rabbitmq:
    host: 192.168.188.200
    port: 5672
    username: amo
    password: 123456
    virtualHost: /
    publisher-confirm-type: correlated
    publisher-returns: true
  elasticsearch:
    rest:
      uris: 192.168.188.200:9200
      connection-timeout: 1s
      read-timeout: 30s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/es?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: amo233

