server:
  port: 8888

spring:
  profiles:
    active: amo   # 对应自己开发的环境
  application:
    name: es-product

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
